import type { Abi, Address } from "viem";

function toAddress(value: string | undefined): Address | undefined {
  if (!value || !/^0x[a-fA-F0-9]{40}$/.test(value)) return undefined;
  return value as Address;
}

export const communityContracts = {
  factory: toAddress(process.env.NEXT_PUBLIC_V3_FACTORY_ADDRESS),
  adminActionsLibrary: toAddress(process.env.NEXT_PUBLIC_V3_ADMIN_ACTIONS_LIBRARY_ADDRESS),
};

const communityDeployment = {
  components: [
    { name: "creator", type: "address" },
    { name: "hub", type: "address" },
    { name: "treasury", type: "address" },
    { name: "createdAt", type: "uint64" },
  ],
  name: "",
  type: "tuple",
} as const;

const communityConfig = {
  components: [
    { name: "name", type: "string" },
    { name: "metadataURI", type: "string" },
    { name: "usdc", type: "address" },
    { name: "globalBertReserve", type: "address" },
    { name: "initialAdmins", type: "address[]" },
    { name: "initialValidators", type: "address[]" },
    { name: "entryStakeUSDC", type: "uint256" },
    { name: "proposalBondUSDC", type: "uint256" },
    { name: "voteMinStakeUSDC", type: "uint256" },
    { name: "membershipExitCooldown", type: "uint256" },
    { name: "validatorApprovalThreshold", type: "uint256" },
    { name: "adminApprovalThreshold", type: "uint256" },
    { name: "binaryRejectionFeeBps", type: "uint256" },
    { name: "validatorRewardShareBps", type: "uint256" },
    { name: "validationWindow", type: "uint256" },
    { name: "binaryVotingDuration", type: "uint256" },
    { name: "roundVotingDuration", type: "uint256" },
    { name: "validatorRewardEpoch", type: "uint256" },
    { name: "validatorActiveThresholdBps", type: "uint256" },
    { name: "validatorProposalPointsThreshold", type: "uint256" },
  ],
  name: "config_",
  type: "tuple",
} as const;

const memberInfo = {
  components: [
    { name: "active", type: "bool" },
    { name: "joinedAt", type: "uint64" },
    { name: "exitRequestedAt", type: "uint64" },
    { name: "membershipStake", type: "uint256" },
    { name: "proposalPoints", type: "uint256" },
  ],
  name: "",
  type: "tuple",
} as const;

const proposal = {
  components: [
    { name: "creator", type: "address" },
    { name: "origin", type: "uint8" },
    { name: "mode", type: "uint8" },
    { name: "status", type: "uint8" },
    { name: "title", type: "string" },
    { name: "description", type: "string" },
    { name: "metadataURI", type: "string" },
    { name: "createdAt", type: "uint64" },
    { name: "validationDeadline", type: "uint64" },
    { name: "votingStartedAt", type: "uint64" },
    { name: "votingDeadline", type: "uint64" },
    { name: "bondAmount", type: "uint256" },
    { name: "yesVotes", type: "uint256" },
    { name: "noVotes", type: "uint256" },
    { name: "approvalCount", type: "uint256" },
    { name: "rejectionCount", type: "uint256" },
    { name: "assignedRoundId", type: "uint256" },
    { name: "roundVotes", type: "uint256" },
    { name: "accepted", type: "bool" },
    { name: "settled", type: "bool" },
  ],
  name: "",
  type: "tuple",
} as const;

const communityRound = {
  components: [
    { name: "origin", type: "uint8" },
    { name: "startTime", type: "uint64" },
    { name: "endTime", type: "uint64" },
    { name: "totalVotes", type: "uint256" },
    { name: "winningProposalId", type: "uint256" },
    { name: "winningVotes", type: "uint256" },
    { name: "settled", type: "bool" },
  ],
  name: "",
  type: "tuple",
} as const;

const withdrawalRequest = {
  components: [
    { name: "to", type: "address" },
    { name: "createdBy", type: "address" },
    { name: "createdAt", type: "uint64" },
    { name: "amount", type: "uint256" },
    { name: "approvalCount", type: "uint256" },
    { name: "reason", type: "string" },
    { name: "metadataURI", type: "string" },
    { name: "executed", type: "bool" },
    { name: "cancelled", type: "bool" },
  ],
  name: "",
  type: "tuple",
} as const;

const validatorRewardEpoch = {
  components: [
    { name: "startTime", type: "uint64" },
    { name: "endTime", type: "uint64" },
    { name: "availableValidationCases", type: "uint256" },
    { name: "rewardAmount", type: "uint256" },
    { name: "activeValidatorCount", type: "uint256" },
    { name: "finalized", type: "bool" },
  ],
  name: "",
  type: "tuple",
} as const;

export const communityFactoryAbi = [
  { type: "event", anonymous: false, name: "CommunityTreasuryCreated", inputs: [{ indexed: true, name: "communityId", type: "uint256" }, { indexed: true, name: "creator", type: "address" }, { indexed: false, name: "treasury", type: "address" }, { indexed: false, name: "configHash", type: "bytes32" }, { indexed: false, name: "name", type: "string" }, { indexed: false, name: "metadataURI", type: "string" }] },
  { type: "function", stateMutability: "view", name: "communityCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "getCommunity", inputs: [{ name: "communityId", type: "uint256" }], outputs: [communityDeployment] },
  { type: "function", stateMutability: "view", name: "getCreatorCommunityIds", inputs: [{ name: "creator", type: "address" }], outputs: [{ type: "uint256[]" }] },
  { type: "function", stateMutability: "view", name: "isActiveCommunityTreasury", inputs: [{ name: "treasury", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", stateMutability: "nonpayable", name: "createCommunity", inputs: [communityConfig], outputs: [{ name: "communityId", type: "uint256" }, { name: "treasury", type: "address" }] },
  { type: "function", stateMutability: "nonpayable", name: "activateCommunity", inputs: [{ name: "communityId", type: "uint256" }, { name: "hub", type: "address" }], outputs: [] },
] as const satisfies Abi;

export const communityHubAbi = [
  { type: "event", anonymous: false, name: "SlateRoundVoteCast", inputs: [{ indexed: true, name: "roundId", type: "uint256" }, { indexed: true, name: "proposalId", type: "uint256" }, { indexed: true, name: "voter", type: "address" }, { indexed: false, name: "amount", type: "uint256" }] },
  { type: "event", anonymous: false, name: "ValidatorEligibilityReached", inputs: [{ indexed: true, name: "member", type: "address" }, { indexed: false, name: "totalPoints", type: "uint256" }] },
  { type: "event", anonymous: false, name: "AdminAdded", inputs: [{ indexed: true, name: "admin", type: "address" }] },
  { type: "event", anonymous: false, name: "AdminRemoved", inputs: [{ indexed: true, name: "admin", type: "address" }] },
  { type: "event", anonymous: false, name: "ValidatorAdded", inputs: [{ indexed: true, name: "validator", type: "address" }] },
  { type: "event", anonymous: false, name: "ValidatorRemoved", inputs: [{ indexed: true, name: "validator", type: "address" }] },
  { type: "event", anonymous: false, name: "AdminActionRequested", inputs: [{ indexed: true, name: "requestId", type: "uint256" }, { indexed: false, name: "action", type: "uint8" }, { indexed: true, name: "proposer", type: "address" }, { indexed: true, name: "target", type: "address" }, { indexed: false, name: "value", type: "uint256" }, { indexed: false, name: "expiresAt", type: "uint256" }] },
  { type: "event", anonymous: false, name: "AdminActionApproved", inputs: [{ indexed: true, name: "requestId", type: "uint256" }, { indexed: true, name: "admin", type: "address" }] },
  { type: "event", anonymous: false, name: "AdminActionExecuted", inputs: [{ indexed: true, name: "requestId", type: "uint256" }, { indexed: false, name: "action", type: "uint8" }, { indexed: true, name: "executor", type: "address" }] },
  { type: "function", stateMutability: "view", name: "creator", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", stateMutability: "view", name: "communityTreasury", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", stateMutability: "view", name: "communityStatus", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", stateMutability: "view", name: "communityTime", inputs: [], outputs: [{ type: "uint64" }] },
  { type: "function", stateMutability: "view", name: "entryStakeUSDC", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "proposalBondUSDC", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "voteMinStakeUSDC", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "membershipExitCooldown", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "validatorProposalPointsThreshold", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "validatorApprovalThreshold", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "validatorActiveThresholdBps", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "adminApprovalThreshold", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "binaryRejectionFeeBps", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "validatorRewardShareBps", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "validationWindow", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "binaryVotingDuration", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "roundVotingDuration", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "validatorRewardEpoch", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "adminCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "pendingValidationProposalCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "activeBinaryProposalCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "activeSlateRoundCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "unresolvedMemberProposalCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "validatorCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "proposalCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "roundCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "activeMemberProposalCount", inputs: [{ name: "member", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "unresolvedVoteLockCount", inputs: [{ name: "member", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "currentValidatorRewardEpochId", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "getValidatorRewardEpoch", inputs: [{ name: "epochId", type: "uint256" }], outputs: [validatorRewardEpoch] },
  { type: "function", stateMutability: "view", name: "isValidatorActiveForEpoch", inputs: [{ name: "epochId", type: "uint256" }, { name: "validator", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", stateMutability: "view", name: "validatorValidationCount", inputs: [{ name: "epochId", type: "uint256" }, { name: "validator", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "getMember", inputs: [{ name: "account", type: "address" }], outputs: [memberInfo] },
  { type: "function", stateMutability: "view", name: "isAdminAccount", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", stateMutability: "view", name: "isValidatorAccount", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", stateMutability: "view", name: "isValidatorEligible", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", stateMutability: "view", name: "validatorDecisionCast", inputs: [{ name: "proposalId", type: "uint256" }, { name: "validator", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", stateMutability: "view", name: "getProposal", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [proposal] },
  { type: "function", stateMutability: "view", name: "getBinaryVote", inputs: [{ name: "proposalId", type: "uint256" }, { name: "voter", type: "address" }], outputs: [{ name: "choice", type: "uint8" }, { name: "stake", type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "getRound", inputs: [{ name: "roundId", type: "uint256" }], outputs: [communityRound] },
  { type: "function", stateMutability: "view", name: "getRoundProposalIds", inputs: [{ name: "roundId", type: "uint256" }], outputs: [{ type: "uint256[]" }] },
  { type: "function", stateMutability: "view", name: "selectedProposalByRound", inputs: [{ name: "roundId", type: "uint256" }, { name: "voter", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "nonpayable", name: "joinCommunity", inputs: [], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "createAdminActionRequest", inputs: [{ name: "action", type: "uint8" }, { name: "target", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ name: "requestId", type: "uint256" }] },
  { type: "function", stateMutability: "nonpayable", name: "approveAdminActionRequest", inputs: [{ name: "requestId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "executeAdminActionRequest", inputs: [{ name: "requestId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "renounceValidatorRole", inputs: [], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "requestMembershipExit", inputs: [], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "finalizeMembershipExit", inputs: [], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "createAdminProposal", inputs: [{ name: "title", type: "string" }, { name: "description", type: "string" }, { name: "metadataURI", type: "string" }], outputs: [{ name: "proposalId", type: "uint256" }] },
  { type: "function", stateMutability: "nonpayable", name: "createMemberProposal", inputs: [{ name: "title", type: "string" }, { name: "description", type: "string" }, { name: "metadataURI", type: "string" }], outputs: [{ name: "proposalId", type: "uint256" }] },
  { type: "function", stateMutability: "nonpayable", name: "createAdminSlateProposal", inputs: [{ name: "title", type: "string" }, { name: "description", type: "string" }, { name: "metadataURI", type: "string" }], outputs: [{ name: "proposalId", type: "uint256" }] },
  { type: "function", stateMutability: "nonpayable", name: "createMemberSlateProposal", inputs: [{ name: "title", type: "string" }, { name: "description", type: "string" }, { name: "metadataURI", type: "string" }], outputs: [{ name: "proposalId", type: "uint256" }] },
  { type: "function", stateMutability: "nonpayable", name: "castValidationDecision", inputs: [{ name: "proposalId", type: "uint256" }, { name: "approved", type: "bool" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "finalizeMemberProposalValidation", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "openBinaryVoting", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "castBinaryVote", inputs: [{ name: "proposalId", type: "uint256" }, { name: "choice", type: "uint8" }, { name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "settleBinaryProposal", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "clearSettledVoteLock", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "createAdminSlateRound", inputs: [{ name: "proposalIds", type: "uint256[]" }], outputs: [{ name: "roundId", type: "uint256" }] },
  { type: "function", stateMutability: "nonpayable", name: "createMemberSlateRound", inputs: [{ name: "proposalIds", type: "uint256[]" }], outputs: [{ name: "roundId", type: "uint256" }] },
  { type: "function", stateMutability: "nonpayable", name: "castSlateRoundVote", inputs: [{ name: "roundId", type: "uint256" }, { name: "proposalId", type: "uint256" }, { name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "settleSlateRound", inputs: [{ name: "roundId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "clearSettledRoundVoteLock", inputs: [{ name: "roundId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "finalizeValidatorRewardEpoch", inputs: [{ name: "epochId", type: "uint256" }], outputs: [] },
] as const satisfies Abi;

export const communityTreasuryAbi = [
  { type: "function", stateMutability: "view", name: "usdc", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", stateMutability: "view", name: "executionBalance", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "availableExecutionBalance", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "validatorRewardBalance", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "totalMembershipLocked", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "totalProposalBondLocked", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "totalRefundLiability", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "withdrawalRequestCount", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "hasApprovedWithdrawal", inputs: [{ name: "requestId", type: "uint256" }, { name: "admin", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", stateMutability: "view", name: "getRefundPreview", inputs: [{ name: "proposalId", type: "uint256" }, { name: "voter", type: "address" }], outputs: [{ name: "amount", type: "uint256" }, { name: "available", type: "bool" }] },
  { type: "function", stateMutability: "view", name: "getWithdrawalRequest", inputs: [{ name: "requestId", type: "uint256" }], outputs: [withdrawalRequest] },
  { type: "function", stateMutability: "view", name: "getProposalBond", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [{ name: "amount", type: "uint256" }, { name: "settled", type: "bool" }] },
  { type: "function", stateMutability: "view", name: "rewardPerValidatorByEpoch", inputs: [{ name: "epochId", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "rewardAmountByEpoch", inputs: [{ name: "epochId", type: "uint256" }], outputs: [{ type: "uint256" }] },
  { type: "function", stateMutability: "view", name: "validatorRewardClaimed", inputs: [{ name: "epochId", type: "uint256" }, { name: "validator", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", stateMutability: "nonpayable", name: "claimNoVoteRefund", inputs: [{ name: "proposalId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "claimValidatorReward", inputs: [{ name: "epochId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "createWithdrawalRequest", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }, { name: "reason", type: "string" }, { name: "metadataURI", type: "string" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "approveWithdrawal", inputs: [{ name: "requestId", type: "uint256" }], outputs: [] },
  { type: "function", stateMutability: "nonpayable", name: "executeWithdrawal", inputs: [{ name: "requestId", type: "uint256" }], outputs: [] },
] as const satisfies Abi;
