import {
  BinaryNoWinSettled, BinaryYesWinSettled, MembershipStakeDeposited, MembershipStakeReleased,
  ProposalBondDeposited, ProposalBondReturned, ProposalBondSlashed, RefundClaimed,
  SlateRoundSettled, ValidatorRewardClaimed, ValidatorRewardEpochFinalized,
  WithdrawalApproved, WithdrawalCancelled, WithdrawalExecuted, WithdrawalRequestCreated,
} from "../generated/templates/CommunityTreasury/CommunityTreasury";
import { CommunityValidatorRewardClaim } from "../generated/schema";
import { communityForTreasury, ensureEpoch, ensureMember, ensureProposal, ensureRound, ensureWithdrawal } from "./helpers";

export function handleMembershipStakeDeposited(event: MembershipStakeDeposited): void { const c = communityForTreasury(event.address); if (c == null) return; const m = ensureMember(c, event.params.member, event.block.timestamp); m.membershipStake = event.params.amount; m.save(); }
export function handleMembershipStakeReleased(event: MembershipStakeReleased): void { const c = communityForTreasury(event.address); if (c == null) return; const m = ensureMember(c, event.params.member, event.block.timestamp); m.membershipStake = event.params.amount; m.save(); }
export function handleProposalBondDeposited(event: ProposalBondDeposited): void { const c = communityForTreasury(event.address); if (c == null) return; const p = ensureProposal(c, event.params.proposalId, event.block.timestamp); p.creator = event.params.author; p.bondAmount = event.params.amount; p.bondState = "Locked"; p.save(); }
export function handleProposalBondSlashed(event: ProposalBondSlashed): void { const c = communityForTreasury(event.address); if (c == null) return; const p = ensureProposal(c, event.params.proposalId, event.block.timestamp); p.bondAmount = event.params.amount; p.bondState = "Slashed"; p.save(); }
export function handleProposalBondReturned(event: ProposalBondReturned): void { const c = communityForTreasury(event.address); if (c == null) return; const p = ensureProposal(c, event.params.proposalId, event.block.timestamp); p.creator = event.params.author; p.bondAmount = event.params.amount; p.bondState = "Returned"; p.save(); }
export function handleBinaryYesWinSettled(event: BinaryYesWinSettled): void { const c = communityForTreasury(event.address); if (c == null) return; const p = ensureProposal(c, event.params.proposalId, event.block.timestamp); p.executionAmount = event.params.executionAmount; p.validatorRewardAmount = event.params.validatorReward; p.globalReserveAmount = event.params.globalReserveAmount; p.settled = true; p.save(); }
export function handleBinaryNoWinSettled(event: BinaryNoWinSettled): void { const c = communityForTreasury(event.address); if (c == null) return; const p = ensureProposal(c, event.params.proposalId, event.block.timestamp); p.refundLiability = event.params.refundLiability; p.globalReserveAmount = event.params.globalReserveAmount; p.settled = true; p.save(); }
export function handleRefundClaimed(event: RefundClaimed): void { const c = communityForTreasury(event.address); if (c == null) return; const p = ensureProposal(c, event.params.proposalId, event.block.timestamp); p.refundLiability = p.refundLiability.minus(event.params.amount); p.save(); }
export function handleTreasurySlateRoundSettled(event: SlateRoundSettled): void { const c = communityForTreasury(event.address); if (c == null) return; const r = ensureRound(c, event.params.roundId, event.block.timestamp); r.executionAmount = event.params.executionAmount; r.validatorRewardAmount = event.params.validatorReward; r.settled = true; r.save(); }
export function handleTreasuryValidatorRewardEpochFinalized(event: ValidatorRewardEpochFinalized): void { const c = communityForTreasury(event.address); if (c == null) return; const e = ensureEpoch(c, event.params.epochId, event.block.timestamp); e.rewardPerValidator = event.params.rewardPerValidator; e.activeValidatorCount = event.params.activeValidatorCount; e.finalized = true; e.save(); }
export function handleValidatorRewardClaimed(event: ValidatorRewardClaimed): void { const c = communityForTreasury(event.address); if (c == null) return; const e = ensureEpoch(c, event.params.epochId, event.block.timestamp); const claim = new CommunityValidatorRewardClaim(event.transaction.hash.toHex() + "-" + event.logIndex.toString()); claim.epoch = e.id; claim.validator = event.params.validator; claim.amount = event.params.amount; claim.timestamp = event.block.timestamp; claim.txHash = event.transaction.hash; claim.save(); }
export function handleWithdrawalRequestCreated(event: WithdrawalRequestCreated): void { const c = communityForTreasury(event.address); if (c == null) return; const w = ensureWithdrawal(c, event.params.requestId, event.block.timestamp); w.creator = event.params.creator; w.recipient = event.params.to; w.amount = event.params.amount; w.reason = event.params.reason; w.metadataURI = event.params.metadataURI; w.approvals = 1; w.save(); }
export function handleWithdrawalApproved(event: WithdrawalApproved): void { const c = communityForTreasury(event.address); if (c == null) return; const w = ensureWithdrawal(c, event.params.requestId, event.block.timestamp); w.approvals += 1; w.save(); }
export function handleWithdrawalCancelled(event: WithdrawalCancelled): void { const c = communityForTreasury(event.address); if (c == null) return; const w = ensureWithdrawal(c, event.params.requestId, event.block.timestamp); w.cancelled = true; w.save(); }
export function handleWithdrawalExecuted(event: WithdrawalExecuted): void { const c = communityForTreasury(event.address); if (c == null) return; const w = ensureWithdrawal(c, event.params.requestId, event.block.timestamp); w.recipient = event.params.to; w.amount = event.params.amount; w.executed = true; w.save(); }
