"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { FaArrowLeft, FaArrowRight } from "react-icons/fa6";
import { usePublicClient } from "wagmi";

import { communityContracts, communityHubAbi } from "@/lib/community-contracts";
import { formatCommunityUsdc, formatProposalOrigin, formatProposalStatus } from "@/lib/community";
import { formatDateTimeFromUnix } from "@/lib/dapp-onchain";
import { getCommunityDeployment, getCommunityProposal, type CommunityDeployment, type CommunityProposal } from "@/lib/community-v3";
import { SlateRoundActions } from "@/components/SlateRoundActions";
import { ClientPagination } from "@/components/ClientPagination";

type Round = { origin: number; startTime: bigint; endTime: bigint; totalVotes: bigint; winningProposalId: bigint; winningVotes: bigint; settled: boolean };

export default function SlateRoundDetailsPage() {
  const params = useParams<{ id: string; roundId: string }>(); const communityId = Number(params.id); const roundId = Number(params.roundId); const client = usePublicClient();
  const [community, setCommunity] = useState<CommunityDeployment | null>(null); const [round, setRound] = useState<Round | null>(null); const [proposals, setProposals] = useState<CommunityProposal[]>([]); const [proposalPage, setProposalPage] = useState(1); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let dead = false; async function load() { if (!client || !communityContracts.factory || communityId < 1 || roundId < 1) return; try { const deployment = await getCommunityDeployment(client, communityContracts.factory, BigInt(communityId)); const read = (request: Record<string, unknown>) => (client as { readContract: (value: Record<string, unknown>) => Promise<unknown> }).readContract(request); const [raw, ids] = await Promise.all([read({ address: deployment.hub, abi: communityHubAbi, functionName: "getRound", args: [BigInt(roundId)] }), read({ address: deployment.hub, abi: communityHubAbi, functionName: "getRoundProposalIds", args: [BigInt(roundId)] })]); const value = raw as Record<string, unknown>; const proposalIds = ids as bigint[]; const items = await Promise.all(proposalIds.map((id) => getCommunityProposal(client, deployment.hub, id))); if (!dead) { setCommunity(deployment); setRound({ origin: Number(value.origin), startTime: value.startTime as bigint, endTime: value.endTime as bigint, totalVotes: value.totalVotes as bigint, winningProposalId: value.winningProposalId as bigint, winningVotes: value.winningVotes as bigint, settled: value.settled as boolean }); setProposals(items); } } catch (reason) { if (!dead) setError(reason instanceof Error ? reason.message : "Could not load Slate Round."); } finally { if (!dead) setLoading(false); } } void load(); return () => { dead = true; }; }, [client, communityId, roundId]);
  if (loading) return <p className="rounded-2xl border border-white/10 bg-[#313443] p-5 text-sm text-slate-300">Loading Slate Round...</p>;
  if (error || !round || !community) return <p className="rounded-2xl border border-rose-300/30 bg-rose-400/10 p-5 text-sm text-rose-100">{error ?? "Round not found."}</p>;
  const proposalTotalPages = Math.max(1, Math.ceil(proposals.length / 10)); const currentProposalPage = Math.min(proposalPage, proposalTotalPages); const visibleProposals = proposals.slice((currentProposalPage - 1) * 10, currentProposalPage * 10);
  return <section className="space-y-6"><Link href={`/v3/communities/${communityId}`} className="inline-flex items-center gap-2 text-sm font-semibold text-cyan-200"><FaArrowLeft /> Back to {community.name || `Community #${communityId}`}</Link><div className="rounded-[32px] border border-white/10 bg-[linear-gradient(135deg,#243d48,#20232f_55%,#313443)] p-7 sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan-200">Slate Round #{roundId} · {formatProposalOrigin(round.origin)}</p><h1 className="mt-3 text-4xl font-semibold text-white">{round.settled ? `Winner: Proposal #${round.winningProposalId}` : "One proposal will win."}</h1><div className="mt-6 grid gap-3 sm:grid-cols-4"><Metric label="Candidates" value={proposals.length.toString()} /><Metric label="Total stake" value={`${formatCommunityUsdc(round.totalVotes)} USDC`} /><Metric label={round.settled ? "Winning stake" : "Ends"} value={round.settled ? `${formatCommunityUsdc(round.winningVotes)} USDC` : formatDateTimeFromUnix(round.endTime)} /><Metric label="Started" value={formatDateTimeFromUnix(round.startTime)} /></div><SlateRoundActions hub={community.hub} treasury={community.treasury} roundId={BigInt(roundId)} candidates={proposals.map((proposal) => ({ id: proposal.id, creator: proposal.creator, title: proposal.title }))} settled={round.settled} /></div><div className="rounded-[28px] border border-white/10 bg-[#2a2d3b] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-400">Candidate proposals</p><p className="mt-2 text-sm text-slate-300">Order is read from the contract and is the deterministic tie-break order.</p><div className="mt-6 grid gap-4">{visibleProposals.map((proposal, index) => <Link key={proposal.id.toString()} href={`/v3/communities/${communityId}/proposals/${proposal.id}`} className="flex flex-col gap-4 rounded-2xl border border-white/10 bg-[#313443] p-5 transition hover:border-cyan-300/35 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-cyan-200">Priority {(currentProposalPage - 1) * 10 + index + 1} · Proposal #{proposal.id.toString()}</p><h2 className="mt-2 text-xl font-semibold text-white">{proposal.title}</h2><p className="mt-2 text-sm text-slate-300">{formatProposalStatus(proposal.status)} · {formatCommunityUsdc(proposal.roundVotes)} USDC selected</p></div><FaArrowRight className="text-cyan-200" /></Link>)}</div><ClientPagination currentPage={currentProposalPage} totalItems={proposals.length} pageSize={10} onPageChange={setProposalPage} /></div></section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-slate-950/20 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-white">{value}</p></div>; }
