// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface RolesAwareUpgradeable$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "RolesAwareUpgradeable";
  readonly sourceName: "contracts/BERT/extensions/Roles/RolesAwareUpgradeable.sol";
  readonly abi: [{"inputs":[],"name":"InvalidInitialization","type":"error"},{"inputs":[],"name":"NotInitializing","type":"error"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint64","name":"version","type":"uint64"}],"name":"Initialized","type":"event"},{"inputs":[],"name":"roles","outputs":[{"internalType":"contract RolesRegistryUpgradeable","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/BERT/extensions/Roles/RolesAwareUpgradeable.sol";
  readonly buildInfoId: "solc-0_8_28-70b60c53527deec92c581d343a33b31c4c357bf6";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["RolesAwareUpgradeable"]: RolesAwareUpgradeable$Type;
    ["contracts/BERT/extensions/Roles/RolesAwareUpgradeable.sol:RolesAwareUpgradeable"]: RolesAwareUpgradeable$Type;
  }
}