import Link from "next/link";
import type { ReactNode } from "react";
import { FaArrowRight, FaBuildingColumns, FaCheckDouble, FaPlus, FaUsers } from "react-icons/fa6";

export default function V3OverviewPage() {
  return <section className="space-y-6"><div className="relative overflow-hidden rounded-[34px] border border-cyan-300/20 bg-[linear-gradient(135deg,#123946_0%,#20232f_46%,#313443_100%)] p-7 sm:p-10"><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full bg-cyan-300/15 blur-3xl" /><div className="absolute -bottom-36 left-1/4 h-72 w-72 rounded-full bg-emerald-300/10 blur-3xl" /><div className="relative max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.34em] text-cyan-200">Independent governance infrastructure</p><h1 className="mt-4 font-[var(--font-display)] text-5xl leading-[0.94] text-white sm:text-6xl">Your community. Your rules. Real capital.</h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-slate-300 sm:text-lg">BERT V3 is a separate Community Layer where organizations run local membership, validators, proposals, voting rounds, and a USDC Treasury on-chain.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/v3/create" className="inline-flex items-center gap-2 rounded-full bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950 transition hover:-translate-y-0.5"><FaPlus /> Create community</Link><Link href="/v3/communities" className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-5 py-3 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-white/10">Explore communities <FaArrowRight /></Link></div></div></div><div className="grid gap-4 md:grid-cols-3"><Feature icon={<FaUsers />} title="Stake-gated membership" text="Communities set their own USDC entry stake and exit cooldown." /><Feature icon={<FaCheckDouble />} title="Validator quality gate" text="Member ideas need local validator approval before governance begins." /><Feature icon={<FaBuildingColumns />} title="Community Treasury" text="Winning votes route capital to an admin-quorum execution Treasury." /></div></section>;
}

function Feature({ icon, title, text }: { icon: ReactNode; title: string; text: string }) {
  return <div className="rounded-[26px] border border-white/10 bg-[#2a2d3b] p-6"><span className="text-2xl text-cyan-300">{icon}</span><h2 className="mt-5 text-xl font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-relaxed text-slate-300">{text}</p></div>;
}
